led_toggle.c File Reference
#include `stm32f3xx.h`
*
#include `stm32f3_discovery.h`
*
#include `led_toggle.h`
*
#include `state_machine.h`
*
Functions
void reset ()
void led_red ()
void led_red_orange ()
void led_green ()
void led_green_blink ()
void led_orange_blink ()
void control_traffic_light ()
Function Documentation
void control_traffic_light ()
Definition at line 84 of file led_toggle.c.
References led_green(), led_green_blink(), led_red(), and led_red_orange().
Referenced by main().
void led_green ()
Definition at line 46 of file led_toggle.c.
References reset().
Referenced by control_traffic_light().
void led_green_blink ()
Definition at line 55 of file led_toggle.c.
References reset().
Referenced by control_traffic_light().
void led_orange_blink ()
Definition at line 70 of file led_toggle.c.
References reset().
void led_red ()
Definition at line 27 of file led_toggle.c.
References reset().
Referenced by control_traffic_light().
void led_red_orange ()
Definition at line 36 of file led_toggle.c.
References reset().
Referenced by control_traffic_light().
void reset ()
Definition at line 18 of file led_toggle.c.
Referenced by led_green(), led_green_blink(), led_orange_blink(), led_red(), and led_red_orange().